# Generated by Django 2.2.12 on 2022-03-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='汽车品牌', max_length=50, unique=True, verbose_name='汽车品牌')),
                ('country', models.CharField(help_text='发源国家', max_length=50, verbose_name='发源国家')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('originator', models.CharField(help_text='品牌创始人', max_length=50, verbose_name='品牌创始人')),
            ],
            options={
                'verbose_name': '汽车品牌',
                'verbose_name_plural': '汽车品牌',
                'db_table': 'tb_brand',
            },
        ),
    ]
