# Generated by Django 2.2.12 on 2022-03-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='车型名称', max_length=50, unique=True, verbose_name='车型名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('year_count', models.IntegerField(help_text='年销量', verbose_name='年销量')),
                ('B_id', models.ForeignKey(help_text='品牌ID', on_delete=django.db.models.deletion.CASCADE, to='brand.Brand', verbose_name='品牌ID')),
            ],
            options={
                'verbose_name': '汽车型号',
                'verbose_name_plural': '汽车型号',
                'db_table': 'tb_type',
            },
        ),
    ]
